### ISSUE TITLE
无法运行build.bat

### ISSUE THREAD

**Issue by Yoorkin** [newbe36524/Newbe.Mahua.Plugins.Parrot#1]
你好，
我试着管理员身份运行`Newbe.Mahua.Plugins.Parrot-master\src\CSharp\Http\AspnetCoreNetCoreApp22\MahuaClient`下的build.bat，出现以下错误
![图片](https://user-images.githubusercontent.com/29514144/60897687-135cf300-a29b-11e9-97b9-61971ec247fb.png)
![图片](https://user-images.githubusercontent.com/29514144/60898135-7cdd0180-a29b-11e9-93a1-91507bef696f.png)

其他文件夹下的几个build.bat的情况是一样的
请问如何解决呢？

**Comment by newbe36524** [comment]
这个是因为第一步下载 nuget 的时候下载不成功。你需要一个更加顺畅的带宽环境。

**Comment by Yoorkin** [comment]
> 
> 
> 这个是因为第一步下载 nuget 的时候下载不成功。你需要一个更加顺畅的带宽环境。

好的 谢谢你的回复
